# .github/workflows/main.yml
name: BuildTest
on:
  pull_request:
    branches: [ beta ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install NPM dependencies
        run: npm install
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}
      #     aws-region: us-east-1
      - name: Build and test client. (no deploy)
        run: npm run build 

      # - name: Download `serverless.yml` state from S3  
      #   run: aws s3 cp s3://tony-webapp-serverless-staging-state/serverless.yml serverless.yml

      # - name: Deploy Next.js app
      #   run: npx serverless
            
      # - name: Upload `.serverless` state to S3
      #   run: aws s3 sync .serverless s3://tony-webapp-serverless-staging-state/.serverless --delete      